### PR TITLE
Removing suffix url `/one` in create action

### PR DESCRIPTION
**Pull request by emulienfou**
Submitting this PR to remove the suffix url `/one` in the create action.
I think this was here for test purpose.

### CODE REVIEW

**Comment by ckoliber** [comment]
Hey @emulienfou 

This plugin in fully compatible with [loopback-component-crud](https://github.com/loopback4/loopback-component-crud), the `/one` url is correct

**Comment by emulienfou** [comment]
Hi @ckoliber thanks for the information.
Would have been nice to have this information in the README.md file ;) 

Is it possible to make this suffix override if we are not using this component?

**Comment by ckoliber** [comment]
Dear @emulienfou,

In a meaningful REST api, every resource has single and bulk operations:

For read operations:
  - `GET /resource`: get bulk
  - `GET /resource/{id}`: get single

For update operations:
  - `PUT /resource`: update bulk
  - `PUT /resource/{id}`: update single

For delete operations:
  - `DELETE /resource`: delete bulk
  - `DELETE /resource/{id}`: delete single

For create operations:
  - `POST /resource`: create bulk
  - `POST /resource/one`: create single
  
This plugin is compatible with a bulk supported backend, and accepting this MR will introduce an incompatibility with support of [loopback-component-crud](https://github.com/loopback4/loopback-component-crud) and other bulk supported backends.

You can create a `feature-flag`, for this kind of problem

**Comment by emulienfou** [comment]
Thanks for the explanation @ckoliber. Closing this PR, will use the CRUD component.

**Pull request closed without merging**
